### ISSUE TITLE
add binary classification metrics?

### ISSUE THREAD

**Issue by gionatamettifogo** [analitico/analitico-automl#14]

**Comment by fmardero** [comment]
@gionatamettifogo could be useful to compute the confusion matrix inside the extra metrics function? Will the interface support this graph?

**Comment by gionatamettifogo** [comment]
def test_classification_multiclass_with_identity_strings_custom_loss(self):
ValueError: Rank mismatch: Rank of labels (received 2) should equal rank of logits minus 1 (received 2). [while running 'Run[Trainer]']

----------------------------------------------------------------------
Ran 1 test in 25.375s

**Comment by gionatamettifogo** [comment]
def test_classification_multiclass_with_yes_no_maybe_undecided


test_regression_with_random_integers_custom_loss
ValueError: Dimensions must be equal, but are 0 and 2 for 'head/losses/call_loss_fn/Equal' (op: 'Equal') with input shapes: [0], [2]. [while running 'Run[Trainer]']

**Comment by fmardero** [comment]
b626be616a5b08b47b7c514660fab332e01a4f5d : now everything works as it should.

**Comment by gionatamettifogo** [comment]
> @gionatamettifogo could be useful to compute the confusion matrix inside the extra metrics function? Will the interface support this graph?

yes
