### ISSUE TITLE
automl / create embedding features

### ISSUE THREAD

**Issue by gionatamettifogo** [analitico/analitico-automl#29]
use random weights, do not reuse embeddings for now
will add in later tickets

**Comment by gionatamettifogo** [comment]
INFO:absl:automl_config.max_steps: 10000
ERROR:absl:Value passed to parameter 'x' has DataType int64 not in list of allowed values: bfloat16, float16, float32, float64, complex64, complex128
ERROR:hyperopt.fmin:job exception: Value passed to parameter 'x' has DataType int64 not in list of allowed values: bfloat16, float16, float32, float64, complex64, complex128
ERROR:absl:Value passed to parameter 'x' has DataType int64 not in list of allowed values: bfloat16, float16, float32, float64, complex64, complex128 [while running 'Run[Trainer]']

----------------------------------------------------------------------
Ran 43 tests in 9694.427s

FAILED (errors=3, skipped=5)

Stdout:
Value passed to parameter 'x' has DataType int64 not in list of allowed values: bfloat16, float16, float32, float64, complex64, complex128 [while running 'Run[Trainer]']
##[error]Process completed with exit code 1.
  Complete job

Any ideas if this is related?

**Comment by fmardero** [comment]
Before commit f6ee87b6cd3b7e8492bfae1803dc359334c11a60 we were already passing "4" as embedding size. This should't be the problem. Presumably one of the inputs we are passing as "x" has an integer datatype. Which are the test involved?
