### ISSUE TITLE
automl / verify why precision and recall metrics come out as zeros in amazon test

### ISSUE THREAD

**Issue by gionatamettifogo** [analitico/analitico-automl#34]

**Comment by fmardero** [comment]
The problem is due to the classes imbalance. The model keeps predicting always the most numerous one. I will add a warning before model export that triggers when the model has this behavior. We need to handle class imbalance in our pipeline.

**Comment by gionatamettifogo** [comment]
If we predict the most numerous class, then "precision" should be more than zero...
